### PR TITLE
Lab03 

### PR DESCRIPTION
**Pull request by hding1**

### CODE REVIEW

**Comment by lanthony159** [comment]
Looks good

**Comment by lanthony159** [comment]
@delinsun @hding1 

When you fix an issue, create a pull request for that code change. The 'ichooseu functionality' should be in a separate pull request than the pull request for lab03, and if you have fixed an issue listed in the issues category, then comment 'fixes issue #issue_number'. Refer to the bottom of lab04 page for details.  

"When you complete issues, you make a pull request back to the github.com/UCSB-CS56-Projects version of your repo, and you make a comment in the pull request: fixes issue #5 (for example). The mention of the issue by number, using the # symbol, should turn into into an automatic link to the issue."

**Comment by hding1** [comment]
fixed issue #58 #55 and #50

**Comment by hding1** [comment]
fixed issue #43 by using Heuristic Preferences to increase AI difficulty instead of random.

**Comment by hding1** [comment]
found a issue in JTextArea and fixed it so that it displays instruction and score board in Rock-Paper-Scissors.(I don't know why it works in CSIL machine, but now it works in both mac and windows)

**Pull request merged**
