### PR TITLE
Fix

### PR DESCRIPTION
**Pull request by hding1**
I modified Tic-Tac-Toe Game. Now, it has three different difficulty levels to choose(Difficult, Medium, Easy). However, Difficult and Medium has same algorithm, so it allows future editors to improve AI algorithm. Also, I added feature that make computer AI to switch turns if the opponent wins. I slightly updated the user interface in tic-tac-toe to make it look better. In addition, I fixed a possible bug in GameGUI that used images from github instead of local folder.

### CODE REVIEW

**Comment by hding1** [comment]
Handled NullPointerExceptions and fixed a situation where "tie" message didn't pop up.

**Comment by delinsun** [comment]
fixed issue #45. now there's a branch called gh-pages and build.xml would generate a copy of javadoc to gh-pages when doing "ant javadoc"

**Comment by hding1** [comment]
I fixed a bug when no pokemon is selected and click on I choose you button, the program freeze. Also, I made the JLabels on Player 1 and Player 2 consistent to look better.

**Comment by delinsun** [comment]
fixed issue #49 added screenshot to readme and modified wiki

**Comment by hding1** [comment]
fixed #62 issue in tic-tac-toe

**Pull request merged**
